{% set name = "layoutparser" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0dfb2194c36a5ad1075b8310f3cbc280c00306d1758cef127d20283f7ce085ea

build:
  # skip because of missing pdfplumber
  skip: True  # [py>311]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - numpy
    - opencv
    - scipy
    - pandas
    - pillow
    - pyyaml >=5.1
    - iopath
    - pdfplumber
    - pdf2image

test:
  imports:
    - layoutparser
  commands:
    # skipping pip check because of error
    # pdfplumber X.X.X has requirement pdfminer.six==YYYYMMDD, but you have pdfminer-six 0.0.1.
    #- pip check
  requires:
    - pip

about:
  home: https://layout-parser.github.io
  summary: A unified toolkit for Deep Learning Based Document Image Analysis
  description: |
    LayoutParser aims to provide a wide range of tools that aims to streamline Document Image Analysis (DIA) tasks.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  doc_url: https://layout-parser.readthedocs.io
  dev_url: https://github.com/Layout-Parser/layout-parser


extra:
  recipe-maintainers:
    - boldorider4
  skip-lints:
    - missing_pip_check
