{% set name = "layoutparser" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0dfb2194c36a5ad1075b8310f3cbc280c00306d1758cef127d20283f7ce085ea

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - opencv
    - scipy
    - pandas
    - pillow
    - pyyaml >=5.1
    - iopath
    - pdfplumber
    - pdf2image

test:
  imports:
    - layoutparser
  commands:
    # skipping pip check because of error
    # pdfplumber X.X.X has requirement pdfminer.six==YYYYMMDD, but you have pdfminer-six 0.0.1.
    #- pip check
  requires:
    - pip

about:
  home: https://github.com/Layout-Parser/layout-parser
  summary: A unified toolkit for Deep Learning Based Document Image Analysis
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - boldorider4
